language: csharp
solution: Easly-Number.sln

before_script:
  - wget https://github.com/bmuschko/link-verifier/releases/download/v0.7/link-verifier-0.7-linux-amd64.tar.gz -O /tmp/link-verifier.tar.gz
  - tar -xvf /tmp/link-verifier.tar.gz
  - export PATH=$PATH:$PWD/link-verifier/

install:
- nuget restore Easly-Number.sln
- nuget install NUnit -Version 3.12.0 -OutputDirectory testrunner
- nuget install NUnit.ConsoleRunner -Version 3.10.0 -OutputDirectory testrunner

script:
# TODO: remove the rm below for NUNIT version > 3.12
- rm ./testrunner/NUnit.3.12.0/CHANGES.md
- ./link-verifier > link-verifier-output.txt
- grep -B 1 FAILED link-verifier-output.txt
- msbuild Easly-Number.sln /p:Configuration=Travis
- mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe --trace=Debug --labels=All ./Test-Easly-Number/bin/x64/Travis/Test-Easly-Number.dll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./Easly-Number/bin/x64/Travis
  target_branch: gh-pages
  email: "github-pages-deploy@travis-ci.org"
  on:
    branch: master
